version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://api.chabaqa.io/api
    container_name: chabaqa-frontend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.chabaqa.io/api
      - NEXT_PUBLIC_APP_URL=https://chabaqa.io
      - HOSTNAME=0.0.0.0
    networks:
      - chabaqa-network

networks:
  chabaqa-network:
    driver: bridge
